version: "2"

services:
    mysql: 
        image: "mysql:5.7"
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: lxl
    
    php-fpm:
        build: ./php-fpm
        ports:
            - "9000:9000"
        volumes:
            - /data/wwwroot/:/data/wwwroot/
            - ./php-fpm/Conf/php.ini:/usr/local/etc/php/php.ini:rw
        depends_on:
            - mysql
        
    nginx:
        image: "nginx:1.17"
        ports:
            - "80:80"
        volumes:
            - /data/wwwroot/:/data/wwwroot/
            - /data/log/nginx/:/var/log/nginx/
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php-fpm
